### ISSUE TITLE
This driver is not compatible with the Olimex ESP32-POE rev C board

### ISSUE THREAD

**Issue by MaxValue** [juliagoda/CH341SER#3]
I know, an issue isn't the right place to store this kind of information, but could you at this to a wiki or a list or something?

**Comment by juliagoda** [comment]
Sure

**Comment by DanKoloff** [comment]
Hello,

I am an Olimex employee and I stumbled upon this notice by chance since I recommend your repo to clients that have problems with the default CH340 driver in Ubuntu 22.

I did a number of empirical tests with at least three PCs today with multiple revisions of ESP32-POE (including revision C) and this no longer applies. I also tested with other Olimex-made boards (like ESP32-EVB, ESP32-POE-ISO, ESP32-GATEWAY) and all work fine with the driver from your repo. I am not sure if it was like that in the past but please remove that note since it no longer applies.

Thanks,
Lub/OLIMEX
